---
title: RWA 1
timezone: UTC
collections:
  gallery:
    title: Gallery
    output: false
    gallery_images:
    - file:
      caption:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  testimonials:
    title: Testimonials
    output: true
    permalink: "/testimonials/:path/"
  uploads:
    title: Uploads
    output: true
  images:
    title: images
    output: false
    image:
      file:
      caption:
      class:
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
- scope:
    path: ''
    type: testimonials
  values:
    layout: testimonial
- scope:
    path: ''
    type: gallery
  values:
    gallery:
      file_1:
      caption_1:
      file_2:
      caption_2:
      file_3:
      caption_3:
      file_4:
      caption_4:
      file_5:
      caption_5:
      file_6:
      caption_6:
- scope:
    path: ''
    type: images
  values:
    image:
      file:
      caption:
      class:
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://yourdomain.com
twitter_username: ronald @ twitter
github_username: ronald @ github
markdown: kramdown
permalink: pretty
