---
title: RWA 1
timezone: UTC
collections:
  images:
    title: Custom-Images
    output: true
    image:
      file:
      caption:
      class:
  gallery:
    title: Gallery
    output: true
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  testimonials:
    title: Testimonials
    output: true
    permalink: "/testimonials/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
- scope:
    path: ''
    type: testimonials
  values:
    layout: testimonial
- scope:
    path: ''
    type: galleries
  values:
    gallery:
      image_1:
        file:
        caption:
      image_2:
        file:
        caption:
      image_3:
        file:
        caption:
      image_4:
        file:
        caption:
      image_5:
        file:
        caption:
      image_6:
        file:
        caption:
- scope:
    path: ''
    type: images
  values:
    image:
      file:
      caption:
      class:
- scope:
    path: ''
    type: testimonials
  values:
    portrait-image:
    testifier-url:
- scope:
    path: ''
    type: projects
  values:
    featured-image:
    featured:
    listing-priority: 2
    site-url:
    testifier:
    gallery:
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://yourdomain.com
twitter_username: ronald @ twitter
github_username: ronald @ github
markdown: kramdown
permalink: pretty
