---
title: RWA 1
timezone: UTC
collections:
  gallery:
    title: Gallery
    output: false
    gallery_images:
    - file:
      caption:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:path/"
  testimonials:
    title: Testimonials
    output: true
    permalink: "/testimonials/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
- scope:
    path: ''
    type: testimonials
  values:
    layout: testimonial
- scope:
    path: ''
    type: gallery
  values:
    gallery:
      file:
      caption:
      file:
      caption:
      file:
      caption:
      file:
      caption:
      file:
      caption:
      file:
      caption:
      file:
      caption:
      file:
      caption:
email: your-email@domain.com
description: 'Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.

'
baseurl: ''
url: http://yourdomain.com
twitter_username: ronald @ twitter
github_username: ronald @ github
markdown: kramdown
permalink: pretty
